/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppBookingsRouteImport } from './routes/_app.bookings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppFolioRouteImport } from './routes/_app.folio'
import { Route as AppGuestsRouteImport } from './routes/_app.guests'
import { Route as AppHousekeepingRouteImport } from './routes/_app.housekeeping'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStaffRouteImport } from './routes/_app.staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFolioRoute = AppFolioRouteImport.update({
  id: '/folio',
  path: '/folio',
  getParentRoute: () => AppRoute,
} as any)
const AppGuestsRoute = AppGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AppRoute,
} as any)
const AppHousekeepingRoute = AppHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof AppBookingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/folio': typeof AppFolioRoute
  '/guests': typeof AppGuestsRoute
  '/housekeeping': typeof AppHousekeepingRoute
  '/invoices': typeof AppInvoicesRoute
  '/payments': typeof AppPaymentsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof AppBookingsRoute
  '/dashboard': typeof AppDashboardRoute
  '/folio': typeof AppFolioRoute
  '/guests': typeof AppGuestsRoute
  '/housekeeping': typeof AppHousekeepingRoute
  '/invoices': typeof AppInvoicesRoute
  '/payments': typeof AppPaymentsRoute
  '/rooms': typeof AppRoomsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/folio': typeof AppFolioRoute
  '/_app/guests': typeof AppGuestsRoute
  '/_app/housekeeping': typeof AppHousekeepingRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/rooms': typeof AppRoomsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/folio'
    | '/guests'
    | '/housekeeping'
    | '/invoices'
    | '/payments'
    | '/rooms'
    | '/settings'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/dashboard'
    | '/folio'
    | '/guests'
    | '/housekeeping'
    | '/invoices'
    | '/payments'
    | '/rooms'
    | '/settings'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/bookings'
    | '/_app/dashboard'
    | '/_app/folio'
    | '/_app/guests'
    | '/_app/housekeeping'
    | '/_app/invoices'
    | '/_app/payments'
    | '/_app/rooms'
    | '/_app/settings'
    | '/_app/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/folio': {
      id: '/_app/folio'
      path: '/folio'
      fullPath: '/folio'
      preLoaderRoute: typeof AppFolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/guests': {
      id: '/_app/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof AppGuestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/housekeeping': {
      id: '/_app/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof AppHousekeepingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFolioRoute: typeof AppFolioRoute
  AppGuestsRoute: typeof AppGuestsRoute
  AppHousekeepingRoute: typeof AppHousekeepingRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppRoomsRoute: typeof AppRoomsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFolioRoute: AppFolioRoute,
  AppGuestsRoute: AppGuestsRoute,
  AppHousekeepingRoute: AppHousekeepingRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppRoomsRoute: AppRoomsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
