/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppPartiesRouteImport } from './routes/_app.parties'
import { Route as AppPurchaseRouteImport } from './routes/_app.purchase'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.$invoiceId'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryCategoriesRouteImport } from './routes/_app.inventory.categories'
import { Route as AppInventoryMediaRouteImport } from './routes/_app.inventory.media'
import { Route as AppInventoryMovementsRouteImport } from './routes/_app.inventory.movements'
import { Route as AppInventoryProductsRouteImport } from './routes/_app.inventory.products'
import { Route as AppPartiesIndexRouteImport } from './routes/_app.parties.index'
import { Route as AppPartiesCustomersRouteImport } from './routes/_app.parties.customers'
import { Route as AppPartiesSuppliersRouteImport } from './routes/_app.parties.suppliers'
import { Route as AppPurchaseBillsRouteImport } from './routes/_app.purchase.bills'
import { Route as AppPurchaseNewRouteImport } from './routes/_app.purchase.new'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppSalesInvoicesRouteImport } from './routes/_app.sales.invoices'
import { Route as AppSalesPosRouteImport } from './routes/_app.sales.pos'
import { Route as AppSalesQuotationsRouteImport } from './routes/_app.sales.quotations'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/$invoiceId',
  path: '/print/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMediaRoute = AppInventoryMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppPartiesIndexRoute = AppPartiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AppPartiesCustomersRoute = AppPartiesCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AppPartiesSuppliersRoute = AppPartiesSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AppPurchaseBillsRoute = AppPurchaseBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppPurchaseRoute,
} as any)
const AppPurchaseNewRoute = AppPurchaseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchaseRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesInvoicesRoute = AppSalesInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesPosRoute = AppSalesPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesQuotationsRoute = AppSalesQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppSalesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/parties': typeof AppPartiesRouteWithChildren
  '/purchase': typeof AppPurchaseRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/media': typeof AppInventoryMediaRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/parties/customers': typeof AppPartiesCustomersRoute
  '/parties/suppliers': typeof AppPartiesSuppliersRoute
  '/purchase/bills': typeof AppPurchaseBillsRoute
  '/purchase/new': typeof AppPurchaseNewRoute
  '/sales/invoices': typeof AppSalesInvoicesRoute
  '/sales/pos': typeof AppSalesPosRoute
  '/sales/quotations': typeof AppSalesQuotationsRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/parties/': typeof AppPartiesIndexRoute
  '/sales/': typeof AppSalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/purchase': typeof AppPurchaseRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/media': typeof AppInventoryMediaRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/parties/customers': typeof AppPartiesCustomersRoute
  '/parties/suppliers': typeof AppPartiesSuppliersRoute
  '/purchase/bills': typeof AppPurchaseBillsRoute
  '/purchase/new': typeof AppPurchaseNewRoute
  '/sales/invoices': typeof AppSalesInvoicesRoute
  '/sales/pos': typeof AppSalesPosRoute
  '/sales/quotations': typeof AppSalesQuotationsRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/parties': typeof AppPartiesIndexRoute
  '/sales': typeof AppSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/parties': typeof AppPartiesRouteWithChildren
  '/_app/purchase': typeof AppPurchaseRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/_app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/_app/inventory/media': typeof AppInventoryMediaRoute
  '/_app/inventory/movements': typeof AppInventoryMovementsRoute
  '/_app/inventory/products': typeof AppInventoryProductsRoute
  '/_app/parties/customers': typeof AppPartiesCustomersRoute
  '/_app/parties/suppliers': typeof AppPartiesSuppliersRoute
  '/_app/purchase/bills': typeof AppPurchaseBillsRoute
  '/_app/purchase/new': typeof AppPurchaseNewRoute
  '/_app/sales/invoices': typeof AppSalesInvoicesRoute
  '/_app/sales/pos': typeof AppSalesPosRoute
  '/_app/sales/quotations': typeof AppSalesQuotationsRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/parties/': typeof AppPartiesIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/parties'
    | '/purchase'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/print/$invoiceId'
    | '/inventory/categories'
    | '/inventory/media'
    | '/inventory/movements'
    | '/inventory/products'
    | '/parties/customers'
    | '/parties/suppliers'
    | '/purchase/bills'
    | '/purchase/new'
    | '/sales/invoices'
    | '/sales/pos'
    | '/sales/quotations'
    | '/inventory/'
    | '/parties/'
    | '/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/purchase'
    | '/reports'
    | '/settings'
    | '/print/$invoiceId'
    | '/inventory/categories'
    | '/inventory/media'
    | '/inventory/movements'
    | '/inventory/products'
    | '/parties/customers'
    | '/parties/suppliers'
    | '/purchase/bills'
    | '/purchase/new'
    | '/sales/invoices'
    | '/sales/pos'
    | '/sales/quotations'
    | '/inventory'
    | '/parties'
    | '/sales'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/parties'
    | '/_app/purchase'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/print/$invoiceId'
    | '/_app/inventory/categories'
    | '/_app/inventory/media'
    | '/_app/inventory/movements'
    | '/_app/inventory/products'
    | '/_app/parties/customers'
    | '/_app/parties/suppliers'
    | '/_app/purchase/bills'
    | '/_app/purchase/new'
    | '/_app/sales/invoices'
    | '/_app/sales/pos'
    | '/_app/sales/quotations'
    | '/_app/inventory/'
    | '/_app/parties/'
    | '/_app/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase': {
      id: '/_app/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/print/$invoiceId': {
      id: '/print/$invoiceId'
      path: '/print/$invoiceId'
      fullPath: '/print/$invoiceId'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/categories': {
      id: '/_app/inventory/categories'
      path: '/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/media': {
      id: '/_app/inventory/media'
      path: '/media'
      fullPath: '/inventory/media'
      preLoaderRoute: typeof AppInventoryMediaRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/movements': {
      id: '/_app/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/parties/': {
      id: '/_app/parties/'
      path: '/'
      fullPath: '/parties/'
      preLoaderRoute: typeof AppPartiesIndexRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/_app/parties/customers': {
      id: '/_app/parties/customers'
      path: '/customers'
      fullPath: '/parties/customers'
      preLoaderRoute: typeof AppPartiesCustomersRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/_app/parties/suppliers': {
      id: '/_app/parties/suppliers'
      path: '/suppliers'
      fullPath: '/parties/suppliers'
      preLoaderRoute: typeof AppPartiesSuppliersRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/_app/purchase/bills': {
      id: '/_app/purchase/bills'
      path: '/bills'
      fullPath: '/purchase/bills'
      preLoaderRoute: typeof AppPurchaseBillsRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/purchase/new': {
      id: '/_app/purchase/new'
      path: '/new'
      fullPath: '/purchase/new'
      preLoaderRoute: typeof AppPurchaseNewRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/invoices': {
      id: '/_app/sales/invoices'
      path: '/invoices'
      fullPath: '/sales/invoices'
      preLoaderRoute: typeof AppSalesInvoicesRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/pos': {
      id: '/_app/sales/pos'
      path: '/pos'
      fullPath: '/sales/pos'
      preLoaderRoute: typeof AppSalesPosRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/quotations': {
      id: '/_app/sales/quotations'
      path: '/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof AppSalesQuotationsRouteImport
      parentRoute: typeof AppSalesRoute
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryMediaRoute: typeof AppInventoryMediaRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryMediaRoute: AppInventoryMediaRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppPartiesRouteChildren {
  AppPartiesCustomersRoute: typeof AppPartiesCustomersRoute
  AppPartiesSuppliersRoute: typeof AppPartiesSuppliersRoute
  AppPartiesIndexRoute: typeof AppPartiesIndexRoute
}

const AppPartiesRouteChildren: AppPartiesRouteChildren = {
  AppPartiesCustomersRoute: AppPartiesCustomersRoute,
  AppPartiesSuppliersRoute: AppPartiesSuppliersRoute,
  AppPartiesIndexRoute: AppPartiesIndexRoute,
}

const AppPartiesRouteWithChildren = AppPartiesRoute._addFileChildren(
  AppPartiesRouteChildren,
)

interface AppPurchaseRouteChildren {
  AppPurchaseBillsRoute: typeof AppPurchaseBillsRoute
  AppPurchaseNewRoute: typeof AppPurchaseNewRoute
}

const AppPurchaseRouteChildren: AppPurchaseRouteChildren = {
  AppPurchaseBillsRoute: AppPurchaseBillsRoute,
  AppPurchaseNewRoute: AppPurchaseNewRoute,
}

const AppPurchaseRouteWithChildren = AppPurchaseRoute._addFileChildren(
  AppPurchaseRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesInvoicesRoute: typeof AppSalesInvoicesRoute
  AppSalesPosRoute: typeof AppSalesPosRoute
  AppSalesQuotationsRoute: typeof AppSalesQuotationsRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesInvoicesRoute: AppSalesInvoicesRoute,
  AppSalesPosRoute: AppSalesPosRoute,
  AppSalesQuotationsRoute: AppSalesQuotationsRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppPartiesRoute: typeof AppPartiesRouteWithChildren
  AppPurchaseRoute: typeof AppPurchaseRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppPartiesRoute: AppPartiesRouteWithChildren,
  AppPurchaseRoute: AppPurchaseRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
