/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppPartiesRouteImport } from './routes/_app.parties'
import { Route as AppPurchaseRouteImport } from './routes/_app.purchase'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.$invoiceId'
import { Route as PrintLabelsRouteImport } from './routes/print.labels'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppInventoryCategoriesRouteImport } from './routes/_app.inventory.categories'
import { Route as AppInventoryMediaRouteImport } from './routes/_app.inventory.media'
import { Route as AppInventoryMovementsRouteImport } from './routes/_app.inventory.movements'
import { Route as AppPartiesIndexRouteImport } from './routes/_app.parties.index'
import { Route as AppPartiesCustomersRouteImport } from './routes/_app.parties.customers'
import { Route as AppPartiesSuppliersRouteImport } from './routes/_app.parties.suppliers'
import { Route as AppPurchaseBillsRouteImport } from './routes/_app.purchase.bills'
import { Route as AppPurchaseNewRouteImport } from './routes/_app.purchase.new'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppReportsAnnexure13RouteImport } from './routes/_app.reports.annexure-13'
import { Route as AppReportsCreditNotesRouteImport } from './routes/_app.reports.credit-notes'
import { Route as AppReportsCustomersRouteImport } from './routes/_app.reports.customers'
import { Route as AppReportsLowStockRouteImport } from './routes/_app.reports.low-stock'
import { Route as AppReportsMarginRouteImport } from './routes/_app.reports.margin'
import { Route as AppReportsMonthlyVatSummaryRouteImport } from './routes/_app.reports.monthly-vat-summary'
import { Route as AppReportsPurchasesRouteImport } from './routes/_app.reports.purchases'
import { Route as AppReportsSalesRouteImport } from './routes/_app.reports.sales'
import { Route as AppReportsStandardViewRouteImport } from './routes/_app.reports.standard-view'
import { Route as AppReportsStockRouteImport } from './routes/_app.reports.stock'
import { Route as AppReportsSuppliersRouteImport } from './routes/_app.reports.suppliers'
import { Route as AppReportsTdsRouteImport } from './routes/_app.reports.tds'
import { Route as AppReportsVatRegisterRouteImport } from './routes/_app.reports.vat-register'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppSalesPosRouteImport } from './routes/_app.sales.pos'
import { Route as AppSalesQuotationsRouteImport } from './routes/_app.sales.quotations'
import { Route as AppInventoryProductsIndexRouteImport } from './routes/_app.inventory.products.index'
import { Route as AppInventoryProductsProductIdRouteImport } from './routes/_app.inventory.products.$productId'
import { Route as AppInventoryProductsNewRouteImport } from './routes/_app.inventory.products.new'
import { Route as AppSalesInvoicesIndexRouteImport } from './routes/_app.sales.invoices.index'
import { Route as AppSalesInvoicesInvoiceIdRouteImport } from './routes/_app.sales.invoices.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppPartiesRoute = AppPartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseRoute = AppPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/$invoiceId',
  path: '/print/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintLabelsRoute = PrintLabelsRouteImport.update({
  id: '/print/labels',
  path: '/print/labels',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMediaRoute = AppInventoryMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppPartiesIndexRoute = AppPartiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AppPartiesCustomersRoute = AppPartiesCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AppPartiesSuppliersRoute = AppPartiesSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppPartiesRoute,
} as any)
const AppPurchaseBillsRoute = AppPurchaseBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppPurchaseRoute,
} as any)
const AppPurchaseNewRoute = AppPurchaseNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPurchaseRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAnnexure13Route = AppReportsAnnexure13RouteImport.update({
  id: '/reports/annexure-13',
  path: '/reports/annexure-13',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCreditNotesRoute = AppReportsCreditNotesRouteImport.update({
  id: '/reports/credit-notes',
  path: '/reports/credit-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsCustomersRoute = AppReportsCustomersRouteImport.update({
  id: '/reports/customers',
  path: '/reports/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsLowStockRoute = AppReportsLowStockRouteImport.update({
  id: '/reports/low-stock',
  path: '/reports/low-stock',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsMarginRoute = AppReportsMarginRouteImport.update({
  id: '/reports/margin',
  path: '/reports/margin',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsMonthlyVatSummaryRoute =
  AppReportsMonthlyVatSummaryRouteImport.update({
    id: '/reports/monthly-vat-summary',
    path: '/reports/monthly-vat-summary',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsPurchasesRoute = AppReportsPurchasesRouteImport.update({
  id: '/reports/purchases',
  path: '/reports/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSalesRoute = AppReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsStandardViewRoute = AppReportsStandardViewRouteImport.update({
  id: '/reports/standard-view',
  path: '/reports/standard-view',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsStockRoute = AppReportsStockRouteImport.update({
  id: '/reports/stock',
  path: '/reports/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsSuppliersRoute = AppReportsSuppliersRouteImport.update({
  id: '/reports/suppliers',
  path: '/reports/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsTdsRoute = AppReportsTdsRouteImport.update({
  id: '/reports/tds',
  path: '/reports/tds',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsVatRegisterRoute = AppReportsVatRegisterRouteImport.update({
  id: '/reports/vat-register',
  path: '/reports/vat-register',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesPosRoute = AppSalesPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesQuotationsRoute = AppSalesQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppInventoryProductsIndexRoute =
  AppInventoryProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryProductsProductIdRoute =
  AppInventoryProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AppInventoryRoute,
  } as any)
const AppInventoryProductsNewRoute = AppInventoryProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppSalesInvoicesIndexRoute = AppSalesInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppSalesRoute,
} as any)
const AppSalesInvoicesInvoiceIdRoute =
  AppSalesInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AppSalesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRouteWithChildren
  '/parties': typeof AppPartiesRouteWithChildren
  '/purchase': typeof AppPurchaseRouteWithChildren
  '/sales': typeof AppSalesRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/print/labels': typeof PrintLabelsRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/media': typeof AppInventoryMediaRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/parties/customers': typeof AppPartiesCustomersRoute
  '/parties/suppliers': typeof AppPartiesSuppliersRoute
  '/purchase/bills': typeof AppPurchaseBillsRoute
  '/purchase/new': typeof AppPurchaseNewRoute
  '/reports/annexure-13': typeof AppReportsAnnexure13Route
  '/reports/credit-notes': typeof AppReportsCreditNotesRoute
  '/reports/customers': typeof AppReportsCustomersRoute
  '/reports/low-stock': typeof AppReportsLowStockRoute
  '/reports/margin': typeof AppReportsMarginRoute
  '/reports/monthly-vat-summary': typeof AppReportsMonthlyVatSummaryRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/standard-view': typeof AppReportsStandardViewRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/reports/suppliers': typeof AppReportsSuppliersRoute
  '/reports/tds': typeof AppReportsTdsRoute
  '/reports/vat-register': typeof AppReportsVatRegisterRoute
  '/sales/pos': typeof AppSalesPosRoute
  '/sales/quotations': typeof AppSalesQuotationsRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/parties/': typeof AppPartiesIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/inventory/products/new': typeof AppInventoryProductsNewRoute
  '/sales/invoices/$invoiceId': typeof AppSalesInvoicesInvoiceIdRoute
  '/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/sales/invoices/': typeof AppSalesInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/purchase': typeof AppPurchaseRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/print/labels': typeof PrintLabelsRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/media': typeof AppInventoryMediaRoute
  '/inventory/movements': typeof AppInventoryMovementsRoute
  '/parties/customers': typeof AppPartiesCustomersRoute
  '/parties/suppliers': typeof AppPartiesSuppliersRoute
  '/purchase/bills': typeof AppPurchaseBillsRoute
  '/purchase/new': typeof AppPurchaseNewRoute
  '/reports/annexure-13': typeof AppReportsAnnexure13Route
  '/reports/credit-notes': typeof AppReportsCreditNotesRoute
  '/reports/customers': typeof AppReportsCustomersRoute
  '/reports/low-stock': typeof AppReportsLowStockRoute
  '/reports/margin': typeof AppReportsMarginRoute
  '/reports/monthly-vat-summary': typeof AppReportsMonthlyVatSummaryRoute
  '/reports/purchases': typeof AppReportsPurchasesRoute
  '/reports/sales': typeof AppReportsSalesRoute
  '/reports/standard-view': typeof AppReportsStandardViewRoute
  '/reports/stock': typeof AppReportsStockRoute
  '/reports/suppliers': typeof AppReportsSuppliersRoute
  '/reports/tds': typeof AppReportsTdsRoute
  '/reports/vat-register': typeof AppReportsVatRegisterRoute
  '/sales/pos': typeof AppSalesPosRoute
  '/sales/quotations': typeof AppSalesQuotationsRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/parties': typeof AppPartiesIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/inventory/products/new': typeof AppInventoryProductsNewRoute
  '/sales/invoices/$invoiceId': typeof AppSalesInvoicesInvoiceIdRoute
  '/inventory/products': typeof AppInventoryProductsIndexRoute
  '/sales/invoices': typeof AppSalesInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRouteWithChildren
  '/_app/parties': typeof AppPartiesRouteWithChildren
  '/_app/purchase': typeof AppPurchaseRouteWithChildren
  '/_app/sales': typeof AppSalesRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
  '/print/labels': typeof PrintLabelsRoute
  '/_app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/_app/inventory/media': typeof AppInventoryMediaRoute
  '/_app/inventory/movements': typeof AppInventoryMovementsRoute
  '/_app/parties/customers': typeof AppPartiesCustomersRoute
  '/_app/parties/suppliers': typeof AppPartiesSuppliersRoute
  '/_app/purchase/bills': typeof AppPurchaseBillsRoute
  '/_app/purchase/new': typeof AppPurchaseNewRoute
  '/_app/reports/annexure-13': typeof AppReportsAnnexure13Route
  '/_app/reports/credit-notes': typeof AppReportsCreditNotesRoute
  '/_app/reports/customers': typeof AppReportsCustomersRoute
  '/_app/reports/low-stock': typeof AppReportsLowStockRoute
  '/_app/reports/margin': typeof AppReportsMarginRoute
  '/_app/reports/monthly-vat-summary': typeof AppReportsMonthlyVatSummaryRoute
  '/_app/reports/purchases': typeof AppReportsPurchasesRoute
  '/_app/reports/sales': typeof AppReportsSalesRoute
  '/_app/reports/standard-view': typeof AppReportsStandardViewRoute
  '/_app/reports/stock': typeof AppReportsStockRoute
  '/_app/reports/suppliers': typeof AppReportsSuppliersRoute
  '/_app/reports/tds': typeof AppReportsTdsRoute
  '/_app/reports/vat-register': typeof AppReportsVatRegisterRoute
  '/_app/sales/pos': typeof AppSalesPosRoute
  '/_app/sales/quotations': typeof AppSalesQuotationsRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/parties/': typeof AppPartiesIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/inventory/products/$productId': typeof AppInventoryProductsProductIdRoute
  '/_app/inventory/products/new': typeof AppInventoryProductsNewRoute
  '/_app/sales/invoices/$invoiceId': typeof AppSalesInvoicesInvoiceIdRoute
  '/_app/inventory/products/': typeof AppInventoryProductsIndexRoute
  '/_app/sales/invoices/': typeof AppSalesInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inventory'
    | '/parties'
    | '/purchase'
    | '/sales'
    | '/settings'
    | '/print/$invoiceId'
    | '/print/labels'
    | '/inventory/categories'
    | '/inventory/media'
    | '/inventory/movements'
    | '/parties/customers'
    | '/parties/suppliers'
    | '/purchase/bills'
    | '/purchase/new'
    | '/reports/annexure-13'
    | '/reports/credit-notes'
    | '/reports/customers'
    | '/reports/low-stock'
    | '/reports/margin'
    | '/reports/monthly-vat-summary'
    | '/reports/purchases'
    | '/reports/sales'
    | '/reports/standard-view'
    | '/reports/stock'
    | '/reports/suppliers'
    | '/reports/tds'
    | '/reports/vat-register'
    | '/sales/pos'
    | '/sales/quotations'
    | '/inventory/'
    | '/parties/'
    | '/reports/'
    | '/sales/'
    | '/inventory/products/$productId'
    | '/inventory/products/new'
    | '/sales/invoices/$invoiceId'
    | '/inventory/products/'
    | '/sales/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/purchase'
    | '/settings'
    | '/print/$invoiceId'
    | '/print/labels'
    | '/inventory/categories'
    | '/inventory/media'
    | '/inventory/movements'
    | '/parties/customers'
    | '/parties/suppliers'
    | '/purchase/bills'
    | '/purchase/new'
    | '/reports/annexure-13'
    | '/reports/credit-notes'
    | '/reports/customers'
    | '/reports/low-stock'
    | '/reports/margin'
    | '/reports/monthly-vat-summary'
    | '/reports/purchases'
    | '/reports/sales'
    | '/reports/standard-view'
    | '/reports/stock'
    | '/reports/suppliers'
    | '/reports/tds'
    | '/reports/vat-register'
    | '/sales/pos'
    | '/sales/quotations'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/sales'
    | '/inventory/products/$productId'
    | '/inventory/products/new'
    | '/sales/invoices/$invoiceId'
    | '/inventory/products'
    | '/sales/invoices'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/parties'
    | '/_app/purchase'
    | '/_app/sales'
    | '/_app/settings'
    | '/print/$invoiceId'
    | '/print/labels'
    | '/_app/inventory/categories'
    | '/_app/inventory/media'
    | '/_app/inventory/movements'
    | '/_app/parties/customers'
    | '/_app/parties/suppliers'
    | '/_app/purchase/bills'
    | '/_app/purchase/new'
    | '/_app/reports/annexure-13'
    | '/_app/reports/credit-notes'
    | '/_app/reports/customers'
    | '/_app/reports/low-stock'
    | '/_app/reports/margin'
    | '/_app/reports/monthly-vat-summary'
    | '/_app/reports/purchases'
    | '/_app/reports/sales'
    | '/_app/reports/standard-view'
    | '/_app/reports/stock'
    | '/_app/reports/suppliers'
    | '/_app/reports/tds'
    | '/_app/reports/vat-register'
    | '/_app/sales/pos'
    | '/_app/sales/quotations'
    | '/_app/inventory/'
    | '/_app/parties/'
    | '/_app/reports/'
    | '/_app/sales/'
    | '/_app/inventory/products/$productId'
    | '/_app/inventory/products/new'
    | '/_app/sales/invoices/$invoiceId'
    | '/_app/inventory/products/'
    | '/_app/sales/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
  PrintLabelsRoute: typeof PrintLabelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parties': {
      id: '/_app/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof AppPartiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase': {
      id: '/_app/purchase'
      path: '/purchase'
      fullPath: '/purchase'
      preLoaderRoute: typeof AppPurchaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/print/$invoiceId': {
      id: '/print/$invoiceId'
      path: '/print/$invoiceId'
      fullPath: '/print/$invoiceId'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/labels': {
      id: '/print/labels'
      path: '/print/labels'
      fullPath: '/print/labels'
      preLoaderRoute: typeof PrintLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/categories': {
      id: '/_app/inventory/categories'
      path: '/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/media': {
      id: '/_app/inventory/media'
      path: '/media'
      fullPath: '/inventory/media'
      preLoaderRoute: typeof AppInventoryMediaRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/movements': {
      id: '/_app/inventory/movements'
      path: '/movements'
      fullPath: '/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/parties/': {
      id: '/_app/parties/'
      path: '/'
      fullPath: '/parties/'
      preLoaderRoute: typeof AppPartiesIndexRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/_app/parties/customers': {
      id: '/_app/parties/customers'
      path: '/customers'
      fullPath: '/parties/customers'
      preLoaderRoute: typeof AppPartiesCustomersRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/_app/parties/suppliers': {
      id: '/_app/parties/suppliers'
      path: '/suppliers'
      fullPath: '/parties/suppliers'
      preLoaderRoute: typeof AppPartiesSuppliersRouteImport
      parentRoute: typeof AppPartiesRoute
    }
    '/_app/purchase/bills': {
      id: '/_app/purchase/bills'
      path: '/bills'
      fullPath: '/purchase/bills'
      preLoaderRoute: typeof AppPurchaseBillsRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/purchase/new': {
      id: '/_app/purchase/new'
      path: '/new'
      fullPath: '/purchase/new'
      preLoaderRoute: typeof AppPurchaseNewRouteImport
      parentRoute: typeof AppPurchaseRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/annexure-13': {
      id: '/_app/reports/annexure-13'
      path: '/reports/annexure-13'
      fullPath: '/reports/annexure-13'
      preLoaderRoute: typeof AppReportsAnnexure13RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/credit-notes': {
      id: '/_app/reports/credit-notes'
      path: '/reports/credit-notes'
      fullPath: '/reports/credit-notes'
      preLoaderRoute: typeof AppReportsCreditNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/customers': {
      id: '/_app/reports/customers'
      path: '/reports/customers'
      fullPath: '/reports/customers'
      preLoaderRoute: typeof AppReportsCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/low-stock': {
      id: '/_app/reports/low-stock'
      path: '/reports/low-stock'
      fullPath: '/reports/low-stock'
      preLoaderRoute: typeof AppReportsLowStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/margin': {
      id: '/_app/reports/margin'
      path: '/reports/margin'
      fullPath: '/reports/margin'
      preLoaderRoute: typeof AppReportsMarginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/monthly-vat-summary': {
      id: '/_app/reports/monthly-vat-summary'
      path: '/reports/monthly-vat-summary'
      fullPath: '/reports/monthly-vat-summary'
      preLoaderRoute: typeof AppReportsMonthlyVatSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/purchases': {
      id: '/_app/reports/purchases'
      path: '/reports/purchases'
      fullPath: '/reports/purchases'
      preLoaderRoute: typeof AppReportsPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/sales': {
      id: '/_app/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AppReportsSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/standard-view': {
      id: '/_app/reports/standard-view'
      path: '/reports/standard-view'
      fullPath: '/reports/standard-view'
      preLoaderRoute: typeof AppReportsStandardViewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/stock': {
      id: '/_app/reports/stock'
      path: '/reports/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof AppReportsStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/suppliers': {
      id: '/_app/reports/suppliers'
      path: '/reports/suppliers'
      fullPath: '/reports/suppliers'
      preLoaderRoute: typeof AppReportsSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/tds': {
      id: '/_app/reports/tds'
      path: '/reports/tds'
      fullPath: '/reports/tds'
      preLoaderRoute: typeof AppReportsTdsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/vat-register': {
      id: '/_app/reports/vat-register'
      path: '/reports/vat-register'
      fullPath: '/reports/vat-register'
      preLoaderRoute: typeof AppReportsVatRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/pos': {
      id: '/_app/sales/pos'
      path: '/pos'
      fullPath: '/sales/pos'
      preLoaderRoute: typeof AppSalesPosRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/quotations': {
      id: '/_app/sales/quotations'
      path: '/quotations'
      fullPath: '/sales/quotations'
      preLoaderRoute: typeof AppSalesQuotationsRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/inventory/products/': {
      id: '/_app/inventory/products/'
      path: '/products'
      fullPath: '/inventory/products/'
      preLoaderRoute: typeof AppInventoryProductsIndexRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products/$productId': {
      id: '/_app/inventory/products/$productId'
      path: '/products/$productId'
      fullPath: '/inventory/products/$productId'
      preLoaderRoute: typeof AppInventoryProductsProductIdRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/inventory/products/new': {
      id: '/_app/inventory/products/new'
      path: '/products/new'
      fullPath: '/inventory/products/new'
      preLoaderRoute: typeof AppInventoryProductsNewRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/_app/sales/invoices/': {
      id: '/_app/sales/invoices/'
      path: '/invoices'
      fullPath: '/sales/invoices/'
      preLoaderRoute: typeof AppSalesInvoicesIndexRouteImport
      parentRoute: typeof AppSalesRoute
    }
    '/_app/sales/invoices/$invoiceId': {
      id: '/_app/sales/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/sales/invoices/$invoiceId'
      preLoaderRoute: typeof AppSalesInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppSalesRoute
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryMediaRoute: typeof AppInventoryMediaRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppInventoryProductsProductIdRoute: typeof AppInventoryProductsProductIdRoute
  AppInventoryProductsNewRoute: typeof AppInventoryProductsNewRoute
  AppInventoryProductsIndexRoute: typeof AppInventoryProductsIndexRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryMediaRoute: AppInventoryMediaRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppInventoryProductsProductIdRoute: AppInventoryProductsProductIdRoute,
  AppInventoryProductsNewRoute: AppInventoryProductsNewRoute,
  AppInventoryProductsIndexRoute: AppInventoryProductsIndexRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppPartiesRouteChildren {
  AppPartiesCustomersRoute: typeof AppPartiesCustomersRoute
  AppPartiesSuppliersRoute: typeof AppPartiesSuppliersRoute
  AppPartiesIndexRoute: typeof AppPartiesIndexRoute
}

const AppPartiesRouteChildren: AppPartiesRouteChildren = {
  AppPartiesCustomersRoute: AppPartiesCustomersRoute,
  AppPartiesSuppliersRoute: AppPartiesSuppliersRoute,
  AppPartiesIndexRoute: AppPartiesIndexRoute,
}

const AppPartiesRouteWithChildren = AppPartiesRoute._addFileChildren(
  AppPartiesRouteChildren,
)

interface AppPurchaseRouteChildren {
  AppPurchaseBillsRoute: typeof AppPurchaseBillsRoute
  AppPurchaseNewRoute: typeof AppPurchaseNewRoute
}

const AppPurchaseRouteChildren: AppPurchaseRouteChildren = {
  AppPurchaseBillsRoute: AppPurchaseBillsRoute,
  AppPurchaseNewRoute: AppPurchaseNewRoute,
}

const AppPurchaseRouteWithChildren = AppPurchaseRoute._addFileChildren(
  AppPurchaseRouteChildren,
)

interface AppSalesRouteChildren {
  AppSalesPosRoute: typeof AppSalesPosRoute
  AppSalesQuotationsRoute: typeof AppSalesQuotationsRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppSalesInvoicesInvoiceIdRoute: typeof AppSalesInvoicesInvoiceIdRoute
  AppSalesInvoicesIndexRoute: typeof AppSalesInvoicesIndexRoute
}

const AppSalesRouteChildren: AppSalesRouteChildren = {
  AppSalesPosRoute: AppSalesPosRoute,
  AppSalesQuotationsRoute: AppSalesQuotationsRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppSalesInvoicesInvoiceIdRoute: AppSalesInvoicesInvoiceIdRoute,
  AppSalesInvoicesIndexRoute: AppSalesInvoicesIndexRoute,
}

const AppSalesRouteWithChildren = AppSalesRoute._addFileChildren(
  AppSalesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppPartiesRoute: typeof AppPartiesRouteWithChildren
  AppPurchaseRoute: typeof AppPurchaseRouteWithChildren
  AppSalesRoute: typeof AppSalesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppReportsAnnexure13Route: typeof AppReportsAnnexure13Route
  AppReportsCreditNotesRoute: typeof AppReportsCreditNotesRoute
  AppReportsCustomersRoute: typeof AppReportsCustomersRoute
  AppReportsLowStockRoute: typeof AppReportsLowStockRoute
  AppReportsMarginRoute: typeof AppReportsMarginRoute
  AppReportsMonthlyVatSummaryRoute: typeof AppReportsMonthlyVatSummaryRoute
  AppReportsPurchasesRoute: typeof AppReportsPurchasesRoute
  AppReportsSalesRoute: typeof AppReportsSalesRoute
  AppReportsStandardViewRoute: typeof AppReportsStandardViewRoute
  AppReportsStockRoute: typeof AppReportsStockRoute
  AppReportsSuppliersRoute: typeof AppReportsSuppliersRoute
  AppReportsTdsRoute: typeof AppReportsTdsRoute
  AppReportsVatRegisterRoute: typeof AppReportsVatRegisterRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppPartiesRoute: AppPartiesRouteWithChildren,
  AppPurchaseRoute: AppPurchaseRouteWithChildren,
  AppSalesRoute: AppSalesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppReportsAnnexure13Route: AppReportsAnnexure13Route,
  AppReportsCreditNotesRoute: AppReportsCreditNotesRoute,
  AppReportsCustomersRoute: AppReportsCustomersRoute,
  AppReportsLowStockRoute: AppReportsLowStockRoute,
  AppReportsMarginRoute: AppReportsMarginRoute,
  AppReportsMonthlyVatSummaryRoute: AppReportsMonthlyVatSummaryRoute,
  AppReportsPurchasesRoute: AppReportsPurchasesRoute,
  AppReportsSalesRoute: AppReportsSalesRoute,
  AppReportsStandardViewRoute: AppReportsStandardViewRoute,
  AppReportsStockRoute: AppReportsStockRoute,
  AppReportsSuppliersRoute: AppReportsSuppliersRoute,
  AppReportsTdsRoute: AppReportsTdsRoute,
  AppReportsVatRegisterRoute: AppReportsVatRegisterRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
  PrintLabelsRoute: PrintLabelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
